In [6]:
import pandas as pd

dataset = pd.read_csv("data/train.csv")

In [9]:
dataset.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [10]:
len(dataset)

891

In [11]:
dataset.shape

(891, 12)

In [12]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB

In [13]:
dataset.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [14]:
dataset.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [15]:
dataset.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [16]:
dataset["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [17]:
dataset["Survived"].value_counts(normalize=True)

Survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64

In [18]:
pd.crosstab(dataset["Sex"], dataset["Survived"], normalize="index")

Survived         0         1
Sex
female    0.257962  0.742038
male      0.811092  0.188908

In [19]:
features = [
    "Pclass",
    "Sex",
    "Age",
    "SibSp",
    "Parch",
    "Fare",
    "Embarked"
]

X = dataset[features]
y = dataset["Survived"]

In [20]:
X.head()

   Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S

In [22]:
X.isnull().sum()

Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [23]:
dataset["Age"].mean()

np.float64(29.69911764705882)

In [24]:
X["Age"] = X["Age"].fillna(dataset["Age"].mean())

In [25]:
X.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    2
dtype: int64

In [26]:
dataset["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [27]:
X["Embarked"] = X["Embarked"].fillna("S")

In [28]:
X.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [29]:
X["Sex"] = X["Sex"].map({"male": 0, "female": 1})

In [30]:
X.head()

   Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0       3    0  22.0      1      0   7.2500        S
1       1    1  38.0      1      0  71.2833        C
2       3    1  26.0      0      0   7.9250        S
3       1    1  35.0      1      0  53.1000        S
4       3    0  35.0      0      0   8.0500        S

In [31]:
X["Embarked"] = X["Embarked"].map({
    "S": 0,
    "C": 1,
    "Q": 2
})

In [32]:
X.head()

   Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3    0  22.0      1      0   7.2500         0
1       1    1  38.0      1      0  71.2833         1
2       3    1  26.0      0      0   7.9250         0
3       1    1  35.0      1      0  53.1000         0
4       3    0  35.0      0      0   8.0500         0

In [33]:
X.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
X.head()

   Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3    0  22.0      1      0   7.2500         0
1       1    1  38.0      1      0  71.2833         1
2       3    1  26.0      0      0   7.9250         0
3       1    1  35.0      1      0  53.1000         0
4       3    0  35.0      0      0   8.0500         0

In [36]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [37]:
from sklearn.linear_model import LogisticRegression

In [40]:
model = LogisticRegression(max_iter=1000)

In [41]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [42]:
predictions = model.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, predictions)

print(accuracy)

0.7988826815642458

In [43]:
model.coef_

array([[-0.96116806,  2.58066986, -0.03197822, -0.30463792, -0.10397312,
         0.00281721,  0.23441306]])

In [44]:
model.intercept_

array([1.66165537])

In [45]:
X2 = dataset[features].copy()

In [46]:
X2["Age"] = X2["Age"].fillna(dataset["Age"].mean())

In [47]:
X2["Embarked"] = X2["Embarked"].fillna("S")

In [48]:
X2["Sex"] = X2["Sex"].map({
    "male": 0,
    "female": 1
})

In [49]:
X2 = pd.get_dummies(X2, columns=["Embarked"], dtype=int)

In [50]:
X2.head()

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,3,0,22.0,1,0,7.2500,0,0,1
1,1,1,38.0,1,0,71.2833,1,0,0
2,3,1,26.0,0,0,7.9250,0,0,1
3,1,1,35.0,1,0,53.1000,0,0,1
4,3,0,35.0,0,0,8.0500,0,0,1

In [51]:
X2_train, X2_test, y2_train, y2_test = train_test_split(
    X2,
    y,
    test_size=0.2,
    random_state=42
)

In [52]:
model2 = LogisticRegression(max_iter=1000)

model2.fit(X2_train, y2_train)

LogisticRegression(max_iter=1000)

In [53]:
predictions2 = model2.predict(X2_test)

accuracy2 = accuracy_score(y2_test, predictions2)

print(accuracy2)

0.8100558659217877

In [54]:
X3 = dataset[features].copy()

In [55]:
X3["Age"] = X3["Age"].fillna(dataset["Age"].mean())

In [56]:
X3["Embarked"] = X3["Embarked"].fillna("S")

In [57]:
X3["Sex"] = X3["Sex"].map({
    "male": 0,
    "female": 1
})

In [58]:
X3 = pd.get_dummies(X3, columns=["Embarked"], dtype=int)

In [59]:
X3["FamilySize"] = X3["SibSp"] + X3["Parch"] + 1

In [60]:
X3.head()

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S,FamilySize
0,3,0,22.0,1,0,7.2500,0,0,1,2
1,1,1,38.0,1,0,71.2833,1,0,0,2
2,3,1,26.0,0,0,7.9250,0,0,1,1
3,1,1,35.0,1,0,53.1000,0,0,1,2
4,3,0,35.0,0,0,8.0500,0,0,1,1

In [63]:

X0 = X3.copy()

In [64]:
X0.head()

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S,FamilySize
0,3,0,22.0,1,0,7.2500,0,0,1,2
1,1,1,38.0,1,0,71.2833,1,0,0,2
2,3,1,26.0,0,0,7.9250,0,0,1,1
3,1,1,35.0,1,0,53.1000,0,0,1,2
4,3,0,35.0,0,0,8.0500,0,0,1,1

In [65]:
X3_train, X3_test, y3_train, y3_test = train_test_split(
    X3,
    y,
    test_size=0.2,
    random_state=42
)

In [66]:
model3 = LogisticRegression(max_iter=1000)

model3.fit(X3_train, y3_train)

LogisticRegression(max_iter=1000)

In [67]:
predictions3 = model3.predict(X3_test)

accuracy3 = accuracy_score(y3_test, predictions3)

print(accuracy3)

0.8100558659217877

In [69]:
dataset["Name"].head(20)

0                               Braund, Mr. Owen Harris
1     Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss. Laina
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                              Allen, Mr. William Henry
5                                      Moran, Mr. James
6                               McCarthy, Mr. Timothy J
7                        Palsson, Master. Gosta Leonard
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                   Nasser, Mrs. Nicholas (Adele Achem)
10                      Sandstrom, Miss. Marguerite Rut
11                             Bonnell, Miss. Elizabeth
12                       Saundercock, Mr. William Henry
13                          Andersson, Mr. Anders Johan
14                 Vestrom, Miss. Hulda Amanda Adolfina
15                     Hewlett, Mrs. (Mary D Kingcome)
16                                 Rice, Master. Eugene
17                         Williams, Mr. Charles Eugene
18    Vander Planke, Mrs. Julius (Emelia Maria Vande...
19                              Masselmani, Mrs. Fatima
Name: Name, dtype: str

In [70]:
X4 = X0.copy()

In [71]:
X4["Title"] = dataset["Name"].str.split(",").str[1].str.split(".").str[0].str.strip()

In [73]:
X4["Title"].head(20)

0         Mr
1        Mrs
2       Miss
3        Mrs
4         Mr
5         Mr
6         Mr
7     Master
8        Mrs
9        Mrs
10      Miss
11      Miss
12        Mr
13        Mr
14      Miss
15       Mrs
16    Master
17        Mr
18       Mrs
19       Mrs
Name: Title, dtype: object

In [74]:
X4["Title"].value_counts()

Title
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Major             2
Mlle              2
Col               2
Don               1
Mme               1
Ms                1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64

In [75]:
X4 = pd.get_dummies(X4, columns=["Title"], dtype=int)

In [76]:
X4.head()

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S,FamilySize,...,Title_Master,Title_Miss,Title_Mlle,Title_Mme,Title_Mr,Title_Mrs,Title_Ms,Title_Rev,Title_Sir,Title_the Countess
0,3,0,22.0,1,0,7.2500,0,0,1,2,...,0,0,0,0,1,0,0,0,0,0
1,1,1,38.0,1,0,71.2833,1,0,0,2,...,0,0,0,0,0,1,0,0,0,0
2,3,1,26.0,0,0,7.9250,0,0,1,1,...,0,1,0,0,0,0,0,0,0,0
3,1,1,35.0,1,0,53.1000,0,0,1,2,...,0,0,0,0,0,1,0,0,0,0
4,3,0,35.0,0,0,8.0500,0,0,1,1,...,0,0,0,0,1,0,0,0,0,0

In [77]:
X4_train, X4_test, y4_train, y4_test = train_test_split(
    X4,
    y,
    test_size=0.2,
    random_state=42
)

In [78]:
model4 = LogisticRegression(max_iter=1000)

model4.fit(X4_train, y4_train)

LogisticRegression(max_iter=1000)

In [79]:
predictions4 = model4.predict(X4_test)

accuracy4 = accuracy_score(y4_test, predictions4)

print(accuracy4)

0.8156424581005587